download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/jfrog-platform-11.0.6.tar.gz
format_version: 1.0.0
name: platform
namespace: jfrog
server: https://galaxy.ansible.com/api/
signatures: []
version: 11.0.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/jfrog/platform/versions/11.0.6/
