- name: Perform installation
  ansible.builtin.include_tasks: "install.yml"
  when:
    - distribution_enabled
    - not distribution_upgrade_only

- name: Perform upgrade
  ansible.builtin.include_tasks: "upgrade.yml"
  when:
    - distribution_enabled
    - distribution_upgrade_only
