- name: Perform installation
  ansible.builtin.include_tasks: "install.yml"
  when:
    - xray_enabled
    - not xray_upgrade_only

- name: Perform upgrade
  ansible.builtin.include_tasks: "upgrade.yml"
  when:
    - xray_enabled
    - xray_upgrade_only
