#!/bin/bash
if [[ -z $1 || -z $2 ]]; then
	echo "usage: $0 <AWS_ACCESS_KEY_ID> <AWS_SECRET_ACCESS_KEY>"
	exit 1
fi

AWS_ACCESS_KEY_ID="$1"
AWS_SECRET_ACCESS_KEY="$2"
# Setup docker compose
docker container rm -f jenkins vault
docker compose up -d
# Wait for vault container to load
VAULT_RUN_MSG="authenticated to the CLI, so you can immediately begin using Vault."
while ! docker logs vault 2>&1 | grep "$VAULT_RUN_MSG";
do
	sleep .5
done
# Configure vault and store the secret
docker exec -e VAULT_TOKEN="00000000-0000-0000-0000-000000000000" -e VAULT_ADDR="http://127.0.0.1:8200" vault vault kv put secret/aws access_key="$AWS_ACCESS_KEY_ID" secret_key="$AWS_SECRET_ACCESS_KEY"

