---
# defaults file for artifactory_nginx
## For production deployments,You SHOULD change it.
server_name: test.artifactory.com

nginx_daemon: nginx

nginx_worker_processes: 1
artifactory_docker_registry_subdomain: false

artifactory_conf_template: artifactory.conf.j2
nginx_conf_template: nginx.conf.j2
