- name: Install awscli
  hosts: server
  become: yes
  gather_facts: no
  tasks:
    - name: Install unzip
      apt:
        name: unzip
        update_cache: yes

    - name: Check if package is already installed
      stat:
        path: "{{ PATH }}"
      register: stat_aws
    
    - name: Install aws cli
      when: not stat_aws.stat.exists
      block:
        - name: Check if package is already installed
          stat:
            path: "{{ PATH }}"
          register: stat_aws

        - name: Fetch aws package
          uri:
            url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: "{{ PATH }}"
   
        - name: Unzip package
          unarchive: 
            src: "{{ PATH }}"
            dest: "{{ UNARCHIVE_PATH }}"
            remote_src: yes
    
        - name: Run install script
          command: ./aws/install
          ignore_errors: yes
      
  vars:
    PATH: /tmp/awscliv2.zip
    UNARCHIVE_PATH: /tmp
