- name: Allow openvpn traffic on port 1194
  ufw:
    rule: allow
    port: 1194
    proto: udp

- name: Enable nat for vpn traffic
  command:
    cmd: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o ens5 -j MASQUERADE

- name: Ensure ip_forward is enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

